import Head from 'next/head'
import Enquiries from '../components/Enquiries'
import Extra from '../components/Extra'
import Footer from '../components/Footer'
import Help from '../components/Help'
import Hero from '../components/Hero'
import ReachUs from '../components/ReachUs'
import Service from '../components/Service'


export default function Home() {
  return (
    <div>
      <Head>
        <title>ReadyforWork | Learn in-depth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Service />
        <Enquiries />
        <ReachUs />
        <Help />
        <Extra />
        <Footer />
      </main>

    </div>
  )
}
